export const tasks = [
    {
        id: 1,
        name: "Task 1",
        description: "Brief description of Task 1.",
        dueDate: "2024-12-31",
    },
    {
        id: 2,
        name: "Task 2",
        description: "Brief description of Task 2.",
        dueDate: "2024-12-15",
    },
    {
        id: 3,
        name: "Task 3",
        description: "Overview of Task 3.",
        dueDate: "2024-11-20",
    },
    {
        id: 4,
        name: "Task 4",
        description: "Summary for Task 4.",
        dueDate: "2024-11-25",
    },
    {
        id: 5,
        name: "Task 5",
        description: "Details for Task 5.",
        dueDate: "2024-12-05",
    },
    {
        id: 6,
        name: "Task 6",
        description: "Key points of Task 6.",
        dueDate: "2024-12-10",
    },
    {
        id: 7,
        name: "Task 7",
        description: "Quick notes on Task 7.",
        dueDate: "2024-12-20",
    },
    {
        id: 8,
        name: "Task 8",
        description: "Essentials of Task 8.",
        dueDate: "2024-11-30",
    },
    {
        id: 9,
        name: "Task 9",
        description: "Highlights of Task 9.",
        dueDate: "2024-12-25",
    },
    {
        id: 10,
        name: "Task 10",
        description: "Points regarding Task 10.",
        dueDate: "2024-11-15",
    },
    {
        id: 11,
        name: "Task 11",
        description: "Brief description of Task 1.",
        dueDate: "2024-12-31",
    },
    {
        id: 12,
        name: "Task 12",
        description: "Brief description of Task 2.",
        dueDate: "2024-12-15",
    },
    {
        id: 13,
        name: "Task 13",
        description: "Overview of Task 3.",
        dueDate: "2024-11-20",
    },
    {
        id: 14,
        name: "Task 14",
        description: "Summary for Task 4.",
        dueDate: "2024-11-25",
    },
    {
        id: 15,
        name: "Task 15",
        description: "Details for Task 5.",
        dueDate: "2024-12-05",
    },
    {
        id: 16,
        name: "Task 16",
        description: "Key points of Task 6.",
        dueDate: "2024-12-10",
    },
    {
        id: 17,
        name: "Task 17",
        description: "Quick notes on Task 7.",
        dueDate: "2024-12-20",
    },
    {
        id: 18,
        name: "Task 18",
        description: "Essentials of Task 8.",
        dueDate: "2024-11-30",
    },
    {
        id: 19,
        name: "Task 19",
        description: "Highlights of Task 9.",
        dueDate: "2024-12-25",
    },
    {
        id: 20,
        name: "Task 20",
        description: "Points regarding Task 10.",
        dueDate: "2024-11-15",
    },
    {
        id: 1,
        name: "Task 21",
        description: "Brief description of Task 1.",
        dueDate: "2024-12-31",
    },
    {
        id: 22,
        name: "Task 22",
        description: "Brief description of Task 2.",
        dueDate: "2024-12-15",
    },
    {
        id: 23,
        name: "Task 23",
        description: "Overview of Task 3.",
        dueDate: "2024-11-20",
    },
    {
        id: 24,
        name: "Task 4",
        description: "Summary for Task 4.",
        dueDate: "2024-11-25",
    },
    {
        id: 25,
        name: "Task 25",
        description: "Details for Task 5.",
        dueDate: "2024-12-05",
    },
    {
        id: 26,
        name: "Task 26",
        description: "Key points of Task 6.",
        dueDate: "2024-12-10",
    },
    {
        id: 27,
        name: "Task 27",
        description: "Quick notes on Task 7.",
        dueDate: "2024-12-20",
    },
    {
        id: 28,
        name: "Task 28",
        description: "Essentials of Task 8.",
        dueDate: "2024-11-30",
    },
    {
        id: 29,
        name: "Task 29",
        description: "Highlights of Task 9.",
        dueDate: "2024-12-25",
    },
    {
        id: 30,
        name: "Task 30",
        description: "Points regarding Task 10.",
        dueDate: "2024-11-15",
    },
    {
        id: 31,
        name: "Task 31",
        description: "Brief description of Task 1.",
        dueDate: "2024-12-31",
    },
    {
        id: 32,
        name: "Task 32",
        description: "Brief description of Task 2.",
        dueDate: "2024-12-15",
    },
    {
        id: 33,
        name: "Task 33",
        description: "Overview of Task 3.",
        dueDate: "2024-11-20",
    },
    {
        id: 34,
        name: "Task 34",
        description: "Summary for Task 4.",
        dueDate: "2024-11-25",
    },
    {
        id: 35,
        name: "Task 35",
        description: "Details for Task 5.",
        dueDate: "2024-12-05",
    },
    {
        id: 36,
        name: "Task 36",
        description: "Key points of Task 6.",
        dueDate: "2024-12-10",
    },
    {
        id: 37,
        name: "Task 7",
        description: "Quick notes on Task 7.",
        dueDate: "2024-12-20",
    },
    {
        id: 38,
        name: "Task 38",
        description: "Essentials of Task 8.",
        dueDate: "2024-11-30",
    },
    {
        id: 39,
        name: "Task 39",
        description: "Highlights of Task 9.",
        dueDate: "2024-12-25",
    },
    {
        id: 40,
        name: "Task 40",
        description: "Points regarding Task 10.",
        dueDate: "2024-11-15",
    },
    {
        id: 41,
        name: "Task 41",
        description: "Brief description of Task 1.",
        dueDate: "2024-12-31",
    },
    {
        id: 42,
        name: "Task 42",
        description: "Brief description of Task 2.",
        dueDate: "2024-12-15",
    },
    {
        id: 43,
        name: "Task 43",
        description: "Overview of Task 3.",
        dueDate: "2024-11-20",
    },
    {
        id: 44,
        name: "Task 44",
        description: "Summary for Task 4.",
        dueDate: "2024-11-25",
    },
    {
        id: 45,
        name: "Task 45",
        description: "Details for Task 5.",
        dueDate: "2024-12-05",
    },
    {
        id: 46,
        name: "Task 46",
        description: "Key points of Task 6.",
        dueDate: "2024-12-10",
    },
    {
        id: 47,
        name: "Task 47",
        description: "Quick notes on Task 7.",
        dueDate: "2024-12-20",
    },
    {
        id: 48,
        name: "Task 48",
        description: "Essentials of Task 8.",
        dueDate: "2024-11-30",
    },
    {
        id: 49,
        name: "Task 49",
        description: "Highlights of Task 9.",
        dueDate: "2024-12-25",
    },
    {
        id: 50,
        name: "Task 50",
        description: "Points regarding Task 10.",
        dueDate: "2024-11-15",
    },
    {
        id: 51,
        name: "Task 51",
        description: "Brief description of Task 1.",
        dueDate: "2024-12-31",
    },
    {
        id: 52,
        name: "Task 52",
        description: "Brief description of Task 2.",
        dueDate: "2024-12-15",
    },
    {
        id: 53,
        name: "Task 53",
        description: "Overview of Task 3.",
        dueDate: "2024-11-20",
    },
    {
        id: 54,
        name: "Task 54",
        description: "Summary for Task 4.",
        dueDate: "2024-11-25",
    },
    {
        id: 55,
        name: "Task 55",
        description: "Details for Task 5.",
        dueDate: "2024-12-05",
    },
    {
        id: 56,
        name: "Task 56",
        description: "Key points of Task 6.",
        dueDate: "2024-12-10",
    },
    {
        id: 57,
        name: "Task 57",
        description: "Quick notes on Task 7.",
        dueDate: "2024-12-20",
    },
    {
        id: 58,
        name: "Task 58",
        description: "Essentials of Task 8.",
        dueDate: "2024-11-30",
    },
    {
        id: 59,
        name: "Task 59",
        description: "Highlights of Task 9.",
        dueDate: "2024-12-25",
    },
    {
        id: 60,
        name: "Task 60",
        description: "Points regarding Task 10.",
        dueDate: "2024-11-15",
    },
    {
        id: 61,
        name: "Task 61",
        description: "Brief description of Task 1.",
        dueDate: "2024-12-31",
    },
    {
        id: 62,
        name: "Task 62",
        description: "Brief description of Task 2.",
        dueDate: "2024-12-15",
    },
    {
        id: 63,
        name: "Task 63",
        description: "Overview of Task 3.",
        dueDate: "2024-11-20",
    },
    {
        id: 64,
        name: "Task 64",
        description: "Summary for Task 4.",
        dueDate: "2024-11-25",
    },
    {
        id: 65,
        name: "Task 65",
        description: "Details for Task 5.",
        dueDate: "2024-12-05",
    },
    {
        id: 66,
        name: "Task 66",
        description: "Key points of Task 6.",
        dueDate: "2024-12-10",
    },
    {
        id: 67,
        name: "Task 67",
        description: "Quick notes on Task 7.",
        dueDate: "2024-12-20",
    },
    {
        id: 68,
        name: "Task 68",
        description: "Essentials of Task 8.",
        dueDate: "2024-11-30",
    },
    {
        id: 69,
        name: "Task 69",
        description: "Highlights of Task 9.",
        dueDate: "2024-12-25",
    },
    {
        id: 70,
        name: "Task 70",
        description: "Points regarding Task 10.",
        dueDate: "2024-11-15",
    },
    {
        id: 71,
        name: "Task 71",
        description: "Brief description of Task 1.",
        dueDate: "2024-12-31",
    },
    {
        id: 72,
        name: "Task 72",
        description: "Brief description of Task 2.",
        dueDate: "2024-12-15",
    },
    {
        id: 73,
        name: "Task 73",
        description: "Overview of Task 3.",
        dueDate: "2024-11-20",
    },
    {
        id: 74,
        name: "Task 74",
        description: "Summary for Task 4.",
        dueDate: "2024-11-25",
    },
    {
        id: 75,
        name: "Task 75",
        description: "Details for Task 5.",
        dueDate: "2024-12-05",
    },
    {
        id: 76,
        name: "Task 76",
        description: "Key points of Task 6.",
        dueDate: "2024-12-10",
    },
    {
        id: 77,
        name: "Task 77",
        description: "Quick notes on Task 7.",
        dueDate: "2024-12-20",
    },
    {
        id: 78,
        name: "Task 78",
        description: "Essentials of Task 8.",
        dueDate: "2024-11-30",
    },
    {
        id: 79,
        name: "Task 79",
        description: "Highlights of Task 9.",
        dueDate: "2024-12-25",
    },
    {
        id: 80,
        name: "Task 80",
        description: "Points regarding Task 10.",
        dueDate: "2024-11-15",
    },
    {
        id: 81,
        name: "Task 81",
        description: "Brief description of Task 1.",
        dueDate: "2024-12-31",
    },
    {
        id: 82,
        name: "Task 82",
        description: "Brief description of Task 2.",
        dueDate: "2024-12-15",
    },
    {
        id: 83,
        name: "Task 83",
        description: "Overview of Task 3.",
        dueDate: "2024-11-20",
    },
    {
        id: 84,
        name: "Task 84",
        description: "Summary for Task 4.",
        dueDate: "2024-11-25",
    },
    {
        id: 85,
        name: "Task 85",
        description: "Details for Task 5.",
        dueDate: "2024-12-05",
    },
    {
        id: 86,
        name: "Task 86",
        description: "Key points of Task 6.",
        dueDate: "2024-12-10",
    },
    {
        id: 87,
        name: "Task 87",
        description: "Quick notes on Task 7.",
        dueDate: "2024-12-20",
    },
    {
        id: 88,
        name: "Task 88",
        description: "Essentials of Task 8.",
        dueDate: "2024-11-30",
    },
    {
        id: 89,
        name: "Task 89",
        description: "Highlights of Task 9.",
        dueDate: "2024-12-25",
    },
    {
        id: 90,
        name: "Task 90",
        description: "Points regarding Task 10.",
        dueDate: "2024-11-15",
    },
    {
        id: 91,
        name: "Task 91",
        description: "Points regarding Task 10.",
        dueDate: "2024-11-15",
    },{
        id: 92,
        name: "Task 92",
        description: "Points regarding Task 10.",
        dueDate: "2024-11-15",
    },{
        id: 93,
        name: "Task 93",
        description: "Points regarding Task 10.",
        dueDate: "2024-11-15",
    },{
        id: 94,
        name: "Task 94",
        description: "Points regarding Task 10.",
        dueDate: "2024-11-15",
    },{
        id: 95,
        name: "Task 95",
        description: "Points regarding Task 10.",
        dueDate: "2024-11-15",
    },{
        id: 96,
        name: "Task 96",
        description: "Points regarding Task 10.",
        dueDate: "2024-11-15",
    },{
        id: 97,
        name: "Task 97",
        description: "Points regarding Task 10.",
        dueDate: "2024-11-15",
    },{
        id: 98,
        name: "Task 98",
        description: "Points regarding Task 10.",
        dueDate: "2024-11-15",
    },{
        id: 99,
        name: "Task 99",
        description: "Points regarding Task 10.",
        dueDate: "2024-11-15",
    },{
        id: 100,
        name: "Task 100",
        description: "Points regarding Task 10.",
        dueDate: "2024-11-15",
    },
];





// export const generateTasks = (numTasks: number) => {
//     const tasks = [];
//     for (let i = 1; i <= numTasks; i++) {
//       tasks.push({
//         id: i,
//         name: `Task ${i}`,
//         description: `This is the description for task ${i}`,
//         dueDate: new Date(Date.now() + i * 86400000).toLocaleDateString(), // One day after the next
//       });
//     }
//     return tasks;
//   };
//   export const tasks = generateTasks(100);
  